sec03:
  product:
    service: http://localhost:7070/sec03/product/
  user:
    service: http://localhost:7070/sec03/user/
  inventory:
    service: http://localhost:7070/sec03/inventory/
  shipping:
    service: http://localhost:7070/sec03/shipping/


